//
// Generated file, do not edit! Created by nedtool 5.6 from stack/mac/packet/Cr.msg.
//

#ifndef __CR_M_H
#define __CR_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>stack/mac/packet/Cr.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Cr
 * {
 *     double cr;
 * }
 * </pre>
 */
class Cr : public ::omnetpp::cPacket
{
  protected:
    double cr;

  private:
    void copy(const Cr& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Cr&);

  public:
    Cr(const char *name=nullptr, short kind=0);
    Cr(const Cr& other);
    virtual ~Cr();
    Cr& operator=(const Cr& other);
    virtual Cr *dup() const override {return new Cr(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getCr() const;
    virtual void setCr(double cr);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Cr& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Cr& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CR_M_H

